### ISSUE TITLE
UnhandledPromiseRejectionWarning when run command

### ISSUE THREAD

**Issue by psrivastava-rsc** [Theodo-UK/sls-dev-tools#161]
**Describe the bug**
When run sls-dev-tools command (inside serverless project) I get following error, and it keep occurring.

```
(node:25641) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
(node:25641) UnhandledPromiseRejectionWarning: ValidationError: Stack with id undefined-dev does not exist
    at Request.extractError (/usr/local/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/request.js:683:14)            .
    at Request.transition (/usr/local/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

**To Reproduce**
1. Goto serverless project folder in iTerm/Terminal
2. issue command sls-dev-tools

**If relevant**
 - OS: macOS
 - Version Latest
 - Deployment Framework: serverless

**Comment by jnmullen** [comment]
Are you specifying a stack name on the command line when running the tool? Can you supply the full command line being run?

This line from your stack trace above : 

`(node:25641) UnhandledPromiseRejectionWarning: ValidationError: Stack with id undefined-dev does not exist
`

Indicates that the tool cannot find the stack with name undefined-dev within AWS. Is that the stack name you are expecting? I can confirm I see the same error but only when specifying a stack name which does not exist.

**Comment by psrivastava-rsc** [comment]
I am running following command. As you can see I am not supplying stackname
```
sls-dev-tools -r us-east-1
```

**Comment by artoliukkonen** [comment]
Sorry this was my bad. Added PR that fixes it. 

Until it gets merged, you should pass in the stack name manually.

**Comment by psrivastava-rsc** [comment]
Thanks it is better. But when i select function from DashBoard (Right Top) it shows the same UnhandledPromiseRejectionWarning warning.

**Comment by DotGav** [comment]
@artoliukkonen Not sure your PR does fix this issue, I have commented on it!

@psrivastava-rsc If I am understanding correctly you are still getting the above error when you pass the stack name argument, unsure how the stack name is getting set to undefined, I'll look into this further tomorrow! Thanks for opening the issue :)

**Comment by BenEllerby** [comment]
@psrivastava-rsc to help the team looking into this tomorrow would you mind sharing your serverless.yml (redacted as needed). Especially the service and provider sections.

**Comment by psrivastava-rsc** [comment]
Yes @DotGav I am passing stackname with "-n" argument. Thanks for quick reply.

**Comment by DotGav** [comment]
@psrivastava-rsc No worries! Hopefully should be able to find a fix for this tomorrow, additionally, we do have a helper wizard for stack name when one isn't provided (or is undefined as above) in progress which can hopefully get released tomorrow as a priority which should also fix this issue.

**Comment by psrivastava-rsc** [comment]
Hi @BenEllerby, here is simplified version of my serverless.yml.

```yaml
service: ps-master-product-service

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  apiName: product-service
  role: ${file(config.json):config.region.${self:provider.region}.lambda_role_arn}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    VERSION: ${file(package.json):version}
    COMMIT_HASH: ${opt:commit_hash}
```

**Comment by psrivastava-rsc** [comment]
Last patch did not fix the issue. I have updated to 1.0.1. I have tried both with and without supplying stackname.

![Screenshot](https://i.ibb.co/k14dxky/Screen-Shot-2020-04-27-at-08-34-32.png)

**Comment by DotGav** [comment]
@psrivastava-rsc I have released the latest version 1.0.2 now, hopefully, the work @artoliukkonen has done will fix this when no stack name is provided

**Comment by DotGav** [comment]
Let me know if this doesn't work for you and I will reopen the issue and investigate further!

**Comment by psrivastava-rsc** [comment]
I have updated to 1.0.2 it still the same error as screenshot above. 

> UnhandledPromiseRejectionWarning: ResourceNotFoundException: The specified log group does not exist.

**Comment by DotGav** [comment]
@psrivastava-rsc Ok thanks for checking! I will continue investigating this

**Comment by artoliukkonen** [comment]
@psrivastava-rsc one problem might be that `role` you have there. I think it's not automatically loaded by the tool, instead you should pass a `--profile` flag. 

Also, note that the tool sets the default stage to `dev` unless you specify it in parameters.

With #162 at least the stack name is now loaded correctly in 1.0.2, but it looks like it might be good to add support for these other parameters too. It now loads stack name and region from `serverless.yml`.

**Comment by DotGav** [comment]
@psrivastava-rsc New release v1.0.4 may fix this issue, would you be able to check this for me?

**Comment by psrivastava-rsc** [comment]
Yes I have checked 1.0.4. It is not working for me. I can easily replicate on minimal code below.

```sh
.
├── package.json
├── routes
│   └── healthCheckRoutes.ts
├── serverless.yml
└── tsconfig.json
```
### serverless.yml
```sh
service: sls-dev-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'develop'}
  region: ${opt:region, 'us-east-1'}
  apiName: product-service

plugins:
  - serverless-offline

functions:
  health-check:
    handler: routes/healthCheckRoutes.handler
    name: sls-dev-api-health-check
    events:
      - http:
          method: GET
          path: /health-check
          cors: true
```

### routes/healthCheckRoutes.ts

```sh
class HealthCheckRoutes {
    public static handler = async (event: any, context: any) => {
        const response: any = { message: 'Health Check for Product Service', event};

        return {
            statusCode: 200,
            body: JSON.stringify(response)
        };
    }
}
module.exports.handler = HealthCheckRoutes.handler ;
```

### package.json

```json
{
  "name": "sls-dev-api",
  "version": "1.0.0",
  "description": "sls dev api",
  "scripts": {
    "offline": "AWS_PROFILE=ps-master-develop sls offline start --region us-east-1"
  },
  "author": "Pujan",
  "devDependencies": {
    "@types/node": "^13.7.7",
    "aws-sdk": "^2.634.0"
  },
  "dependencies": {
    "serverless-offline": "5.12.1"
  }
}
```

**Comment by DotGav** [comment]
@psrivastava-rsc Thank you so much for this! I will work on fixing it with the above examples :)

**Comment by DotGav** [comment]
@psrivastava-rsc The issue is due to us not supporting parsing the ${opt: by default without passing them in (currently we do not error gracefully on this either which I will fix). I believe with the above example running the command will work `sls-dev-tools -r us-east-1 -s develop`

**Comment by psrivastava-rsc** [comment]
Hi @DotGav Yeah I have tried running this command `sls-dev-tools -r us-east-1 -s develop` as mentioned earlier. This is not helping. As you mentioned opt problem, I am now using more simplified serverless.yml file as mentioned below:

```yaml
  ...
  stage: 'develop'
  region: 'us-east-1'
  ...
```

**Comment by zhhz** [comment]
I'm having the same issue... Anyhow, this project looks very promising, keep up the good work...

**Comment by mansurpasha** [comment]
@zhhz @psrivastava-rsc Thanks for letting us know. Currently investigating this issue while making improvements to the tool's error handling

**Comment by mansurpasha** [comment]
@psrivastava-rsc New release v1.0.5 improves a lot of the error handling, so that better error messages display in the console logs. Can you try running this version and letting us know what error message displays?

**Comment by psrivastava-rsc** [comment]
I have updated to 1.0.5. Now it is much better. 

<img width="1522" alt="Screen Shot 2020-05-02 at 09 21 15" src="https://user-images.githubusercontent.com/56028712/80859390-8edbc680-8c58-11ea-9d62-4b0110a390e1.png">

**Comment by mansurpasha** [comment]
@psrivastava-rsc This error message suggests the Lambda hasn't been invoked. I'm going to close this issue for now, if you find that this error continues to display even after the Lambda has been invoked, can you open a new issue?

**Comment by psrivastava-rsc** [comment]
@mansurpasha, lambda has been invoked multiple times. Error persists as mentioned in the picture above.

**Comment by psrivastava-rsc** [comment]
I can try to debug this issue, I can check out source code and if you could let me know how error propagation works here.

**Comment by mansurpasha** [comment]
@psrivastava-rsc After further investigation, we fixed a problem with custom function names which will hopefully resolve the issue you're having. A new version of the tool will be released tomorrow morning!

**Comment by mansurpasha** [comment]
@psrivastava-rsc v1.0.7 has now been released! Let us know if this fixes your problem!
